=== 57459N/Multiagents/src/main/resources/flowers.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Flowers">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Flower" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Name" type="xs:string"/>
                            <xs:element name="Soil">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="Подзолистая"/>
                                        <xs:enumeration value="Грунтовая"/>
                                        <xs:enumeration value="Дерново-подзолистая"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="Origin" type="xs:string"/>
                            <xs:element name="VisualParameters">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Parameter" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:simpleContent>
                                                    <xs:extension base="xs:string">
                                                        <xs:attribute name="type" use="required" type="xs:string"/>
                                                    </xs:extension>
                                                </xs:simpleContent>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="GrowingTips">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Tip" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:simpleContent>
                                                    <xs:extension base="xs:string">
                                                        <xs:attribute name="type" use="required" type="xs:string"/>
                                                    </xs:extension>
                                                </xs:simpleContent>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="Multiplying" type="xs:string"/>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:ID" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== 57459N/Multiagents/src/main/resources/flowers.xml
<?xml version="1.0" encoding="UTF-8"?>
<Flowers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="flowers.xsd">
    <Flower id="flower1">
        <Name>Роза</Name>
        <Soil>Грунтовая</Soil>
        <Origin>Иран</Origin>
        <VisualParameters>
            <Parameter type="stemColor">Красный</Parameter>
            <Parameter type="leafColor">Зеленый</Parameter>
            <Parameter type="averageSize">50 см</Parameter>
        </VisualParameters>
        <GrowingTips>
            <Tip type="temperature">18-24</Tip>
            <Tip type="light">Светолюбиво</Tip>
            <Tip type="watering">200</Tip>
        </GrowingTips>
        <Multiplying>Черенками</Multiplying>
    </Flower>
    <Flower id="flower2">
        <Name>Тюльпан</Name>
        <Soil>Дерново-подзолистая</Soil>
        <Origin>Турция</Origin>
        <VisualParameters>
            <Parameter type="stemColor">Желтый</Parameter>
            <Parameter type="leafColor">Зеленый</Parameter>
            <Parameter type="averageSize">30 см</Parameter>
        </VisualParameters>
        <GrowingTips>
            <Tip type="temperature">15-20</Tip>
            <Tip type="light">Полусвет</Tip>
            <Tip type="watering">150</Tip>
        </GrowingTips>
        <Multiplying>Семена</Multiplying>
    </Flower>
    <!-- Добавьте еще 14 растений для достижения 16 сущностей -->
</Flowers>
